---
title: "old data conversions"
author: "Lara Knapwost"
date: "6 April 2019"
output: html_document
---

### old

Datetime_Intake -  Geburtsdatum in Tagen - Achtung: negative und Null-Werte vorhanden
```{r, eval=F, echo = F}
aac_in_out$calc_age_in <- round(((aac_in_out$datetime_intake - aac_in_out$date_of_birth)/24/60),0)
```

Folgendes können wir für die Datensätze verwenden, bei denen das Geburtsdatum und datetime_outcome nicht vorhanden ist:
Hier wird die Age-Spalte getrennt und das Alter in Tagen berechnet.

```{r, eval=F, echo = F}
aac_in_out$age_upon_intake_num <- as.numeric(sapply(strsplit(as.character(aac_in_out$age_upon_intake), " "), "[", 1))
aac_in_out$age_upon_intake_char <- sapply(strsplit(as.character(aac_in_out$age_upon_intake), " "), "[", 2)

aac_in_out$age_upon_outcome_num <- as.numeric(sapply(strsplit(as.character(aac_in_out$age_upon_outcome), " "), "[", 1))
aac_in_out$age_upon_outcome_char <- sapply(strsplit(as.character(aac_in_out$age_upon_outcome), " "), "[", 2)

function_age <- function(value){
  if (is.element(value, "years")){
    value <- "365"
  }
  else if (is.element(value, "year")){
    value <- "365"
  }
  else if (is.element(value, "month")){
    value <- "30"
  }
  else if (is.element(value, "months")){
    value <- "30"
  }
  else if (is.element(value, "week")){
    value <- "7"
  }
  else if (is.element(value, "weeks")){
    value <- "7"
  }
  else if (is.element(value, "days")){
    value <- "1"
  }
  else if (is.element(value, "day")){
    value <- "1"
  }
  else if (is.na(value))
    value <- "0" ## ggfs nicht richtig
}

aac_in_out$age_upon_intake_char <- sapply(sapply(aac_in_out$age_upon_intake_char, function_age), as.numeric)
aac_in_out$age_upon_outcome_char <- sapply(sapply(aac_in_out$age_upon_outcome_char, function_age), as.numeric)

aac_in_out$age_upon_intake_calc_days <- aac_in_out$age_upon_intake_char * aac_in_out$age_upon_intake_num
aac_in_out$age_upon_outcome_calc_days <- aac_in_out$age_upon_outcome_char * aac_in_out$age_upon_outcome_num ## geht noch nicht, da NAs

```



